import { BaseModel } from './base-model';
export class PatientModel extends BaseModel{
   name:string
   mail:string
   reference1:string
   reference2:string
   reference3:string
   sSN:string
   phone:string
   bornDate:Date
   doctorId:number
   arsId:number
   patientGuid:string
   fatherName:string
   fatherAge:number
   motherName:string
   motherAge:number
   partnerName:string
   partnerAge:number
   civilStatus:string
   childQty:number
   age:number
   hasPreviouslyOperated:boolean
   howOftenOperated:number
   operationSpecification:string
   haveThePatientHadanAccident:boolean
   accidentSpecification:string
   hasAllergySomeMedicine:boolean
   hasAllergySomeMedicineSpecification:string
hasAllergySomeFoodSpecification:string
HasAllergySomeFood:boolean
}