export enum Permission {
  userList = 1,
  userCreate,
  userEdit,
  patientList,
  patientCreate,
  patientEdit,
  doctorList,
  doctorCreate,
  doctorEdit,
  countryList,
  countryCreate,
  countryEdit,
  officeList,
  officeCreate,
  officeEdit,
  scheduleList,
  scheduleCreate,
  scheduleEdit,
  medicalCenterList,
  medicalCenterCreate,
  medicalCenterEdit,
  arsList,
  arsCreate,
  arsEdit
}
